// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aslrmiysodplkbyznmnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbHJtaXlzb2RwbGtieXpubW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNDcyOTksImV4cCI6MjA1NDYyMzI5OX0._3gi11Sa_wFCXWMdhmlwlwTfVvVs9v-HTFFQDLnDaJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);